---
apiVersion: apps/v1 # which api to use for deployment
kind: Deployment # pod - service what kind of service you wnat

metadata:
  name: mongo-deployment
spec:
  selector: #go into this
    matchLabels: # go into this
      app: mongo # look for this label to match with k8
      # Replica set of this with pods
  replicas: 2
  # template to use it's label for k8 service to launch in browser
  template:
    metadata: 
      labels:
        app: mongo
    
    spec:
      containers:
      - name: mongo
        image: muyisanibaba/mongo-db
        ports:
        - containerPort: 27017