---
# Select type of API and type of service
apiVersion: v1
kind: Service
# Meta data for name
metadata:
  name: nginx-svc
  namespace: default # sre
# Spec to include ports selector to connect to the deployment
spec:
  ports:
  - nodePort: 30001 # range is 30000-32768
    port: 80
    targetPort: 80

# Lets define the selector and label to connect to nginx deploy
  selector:
    app: nginx # this label connects service to deployment
  

  type: NodePort # there is clusterIP Node port and loadbalancer