---
apiVersion: apps/v1 # which api to use for deployment
kind: Deployment # pod - service what kind of service you wnat

metadata:
  name: nginx-deployment
spec:
  selector: #go into this
    matchLabels: # go into this
      app: nginx # look for this label to match with k8
      # Replica set of this with pods
  replicas: 3
  # template to use it's label for k8 service to launch in browser
  template:
    metadata: 
      labels:
        app: nginx
    
    spec:
      containers:
      - name: nginx
        image: muyisanibaba/nginx
        ports:
        - containerPort: 80
