---
# Select type of API and type of service
apiVersion: v1
kind: Service
# Meta data for name
metadata:
  name: nodeapp-svc
  namespace: default # sre
# Spec to include ports selector to connect to the deployment
spec:
  ports:
  - nodePort: 30002 # range is 30000-32768
    port: 3000
    targetPort: 3000

# Lets define the selector and label to connect to nginx deploy
  selector:
    app: nodeapp # this label connects service to deployment
  

  type: NodePort # there is clusterIP Node port and loadbalancer