---
apiVersion: apps/v1 # which api to use for deployment
kind: Deployment # pod - service what kind of service you wnat

metadata:
  name: node-app-deployment
spec:
  selector: #go into this
    matchLabels: # go into this
      app: nodeapp # look for this label to match with k8
      # Replica set of this with pods
  replicas: 2
  # template to use it's label for k8 service to launch in browser
  template:
    metadata: 
      labels:
        app: nodeapp
    
    spec:
      containers:
      - name: nodeapp
        image: muyisanibaba/nodejs-app
        ports:
        - containerPort: 3000
        env:
          - name: DB_HOST
            value: mongodb://10.104.66.172/posts
# kubectl exec pod-name env node seeds/seed.js
# pod name: mongo-deployment-68b8fb9744-c7w4v
# kubectl exec node-app-deployment-674b759ccf-bcqhx env node seeds/seed.js
